/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. */

let i, pre, accumulator;

i = 1; pre = 1;
arr = [1, 2];
accumulator = 0;

while ( arr[i] < 4000000) {
    if( arr[i] % 2 == 0 ) {
        accumulator += arr[i];
        console.log(arr[i] + ' is even; sum at ' + accumulator);
    }
    arr.push(arr[i] + arr[i - 1]);
    i++;
}
console.log(arr)

